version: '2.1'

networks:
  app-tier:
    driver: bridge

services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    networks: 
      - app-tier
    volumes:
      - /datastore:/bitnami
  app:
    image: 'user_manager_app:latest'
    depends_on:
      mongodb:
        condition: service_healthy

    networks:
      - app-tier
    ports: 
      - 3000:3000
    command: npm start